version: "3.9"
services:
  myanimelist_downloader:
    image: "ghcr.io/santerihetekivi/myanimelist_downloader:main"
    build: .
    volumes:
      - "./downloads:/app/downloads"
      - ".env:/app/.env"
    command: myanimelist_downloader --download-directory='/app/downloads' --env-file='/app/.env' --anime --manga
